// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://brbqsbvuitdxrtzqyopj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyYnFzYnZ1aXRkeHJ0enF5b3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MDcxNzEsImV4cCI6MjA4Mzk4MzE3MX0.7DsLDZwF_Yxf1yN3MqHC6-fWpMIQSi4z73AHui5A-c0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);